name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest  # Ubuntu is recommended for better compatibility
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for accurate analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarQube Scanner
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectKey: my-cool-project         # ← Change this to your project key
          organization: your-org-name         # ← Only if using SonarCloud
          scannerMode: CLI
          sonarLogin: ${{ secrets.SONAR_TOKEN }}